# Generated by Django 5.2.16 on 2026-09-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('issuer', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('hackathon', 'Hackathon'), ('internship', 'Internship'), ('course', 'Course'), ('workshop', 'Workshop'), ('research', 'Research')], max_length=20)),
                ('date', models.CharField(blank=True, max_length=80)),
                ('file', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=160)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('duration', models.CharField(blank=True, max_length=120)),
                ('responsibilities', models.TextField(blank=True)),
                ('skills_used', models.CharField(blank=True, max_length=240)),
                ('is_placeholder', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('analytics', 'Data Analytics'), ('ai', 'Artificial Intelligence / Machine Learning'), ('development', 'Full-stack Development'), ('uiux', 'UI/UX Design'), ('graphic', 'Graphic Design')], max_length=20)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('role', models.CharField(blank=True, max_length=160)),
                ('technologies', models.CharField(blank=True, max_length=240)),
                ('image', models.CharField(blank=True, max_length=255)),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('figma_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('analytics', 'Data Analytics'), ('development', 'Development'), ('ai', 'AI / Machine Learning'), ('design', 'Design')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['group', 'order', 'name'],
            },
        ),
    ]
